/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nashss.se.noteworthy;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Main method.
     * @param args for main method
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
